backend:
  name: git-gateway
  branch: main

media_folder: "plugins"
public_folder: "/plugins"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Product Name", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "price", label: "Price", widget: "string" }
      - { name: "category", label: "Category", widget: "select", options: ["dresses", "coats", "accessories"] }
      - { name: "image", label: "Image", widget: "image" }
